#!/usr/bin/env bash
# hardware-tune-cache — apply.
#
# Calls `selfdefctl hardware tune --format env-file` and writes the
# result to /etc/selfdef/hardware-tune.env (atomic). Downstream build
# scripts source this file to pick up SELFDEF_HARDWARE_* env vars
# without doing their own hardware probe.
#
# Idempotent. SELFDEF_DRY_RUN=1 aware.

set -euo pipefail

MODULE="hardware-tune-cache"

emit_status() {
    # JSON status line on stdout — the selfdefctl runner pulls the
    # last JSON object from stdout as the authoritative result.
    local status="$1"
    local message="${2:-}"
    printf '{"module":"%s","status":"%s","message":"%s"}\n' \
        "${MODULE}" "${status}" "${message}"
}

OUT_PATH="${SELFDEF_HARDWARE_TUNE_ENV:-/etc/selfdef/hardware-tune.env}"
DRY_RUN="${SELFDEF_DRY_RUN:-0}"

if ! command -v selfdefctl >/dev/null 2>&1; then
    # Module declares selfdefctl as a binary requirement, but be
    # defensive — better a clear status than a partial write.
    emit_status "failed" "selfdefctl not on PATH"
    exit 1
fi

if [ "${DRY_RUN}" = "1" ]; then
    emit_status "skipped" "DRY-RUN — would write ${OUT_PATH}"
    exit 0
fi

# Atomic write: render to tempfile, then rename. The output dir is
# always created (root + 755 like /etc/selfdef is by Debian package
# convention).
out_dir="$(dirname "${OUT_PATH}")"
mkdir -p "${out_dir}"
tmp="$(mktemp "${OUT_PATH}.XXXXXX")"
trap 'rm -f "${tmp}"' EXIT

# Annotate the file so an operator who opens it knows where it came
# from + when (so they can spot a stale cache).
{
    echo "# /etc/selfdef/hardware-tune.env"
    # No render-timestamp — defeats cmp -s idempotency (2026-06-06).
    echo "# Generated by selfdef module hardware-tune-cache (SD-R23)"
    echo "# Source: \`selfdefctl hardware tune --format env-file\`"
    echo "# Re-run \`selfdefctl modules apply\` to refresh."
    echo
    selfdefctl hardware tune --format env-file
} > "${tmp}"

chmod 0644 "${tmp}"
# Idempotency: skip rewrite when content unchanged.
if [[ -f "${OUT_PATH}" ]] && cmp -s "${tmp}" "${OUT_PATH}"; then
    rm -f "${tmp}"
    emit_status "ok" "${OUT_PATH} unchanged"
else
    mv -f "${tmp}" "${OUT_PATH}"
    emit_status "ok" "wrote ${OUT_PATH}"
fi
trap - EXIT
