#!/usr/bin/env bash
# hardware-tune-cache — check. Read-only.
#
# Verifies the cached env file exists, is non-empty, and was
# generated by THIS module. Doesn't re-probe the hardware (apply.sh
# is the canonical write path).

set -euo pipefail

MODULE="hardware-tune-cache"

emit_status() {
    local status="$1"
    local message="${2:-}"
    printf '{"module":"%s","status":"%s","message":"%s"}\n' \
        "${MODULE}" "${status}" "${message}"
}

OUT_PATH="${SELFDEF_HARDWARE_TUNE_ENV:-/etc/selfdef/hardware-tune.env}"

if [ ! -f "${OUT_PATH}" ]; then
    emit_status "failed" "${OUT_PATH} missing — run \`selfdefctl modules apply\`"
    exit 1
fi
if [ ! -s "${OUT_PATH}" ]; then
    emit_status "failed" "${OUT_PATH} empty"
    exit 1
fi
if ! grep -q "SELFDEF_HARDWARE_MARCH=" "${OUT_PATH}"; then
    emit_status "failed" "${OUT_PATH} missing SELFDEF_HARDWARE_MARCH key"
    exit 1
fi
if ! grep -q "hardware-tune-cache (SD-R23)" "${OUT_PATH}"; then
    # Operator may have overwritten the file manually; that's their
    # call but we should report it.
    emit_status "ok" "${OUT_PATH} present (manually-edited; no SD-R23 banner)"
    exit 0
fi
emit_status "ok" "${OUT_PATH} valid + SD-R23-generated"
