//! Dry-run smoke tests for the SD-R23 `hardware-tune-cache` module.
//!
//! End-to-end exercise of the SD-R14..R22 hardware-pipeline arc via
//! a real module:
//!   - manifest carries [requires_hardware] (avx512_vnni + mem ≥ 32 GiB)
//!   - apply.sh calls `selfdefctl hardware tune --format env-file`
//!     (SD-R19) and writes the result atomically to a configured path
//!   - check.sh verifies the file shape (presence of
//!     SELFDEF_HARDWARE_MARCH key + the SD-R23 banner)
//!   - uninstall.sh removes the file (idempotent)
//!
//! Hermetic: each test allocates a scratch path under tempdir; no
//! production /etc/selfdef paths are touched.

use std::process::Command;

mod common;

fn binary() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_BIN_EXE_selfdefctl"))
}

fn module_dir() -> std::path::PathBuf {
    let crate_root = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    crate_root.join("../../modules/hardware-tune-cache")
}

#[test]
fn sdr23_module_manifest_declares_requires_hardware() {
    let manifest = std::fs::read_to_string(module_dir().join("module.toml")).unwrap();
    assert!(
        manifest.contains("[requires_hardware]"),
        "manifest must declare [requires_hardware]: {manifest}"
    );
    assert!(manifest.contains("avx512_vnni"), "must gate on avx512_vnni");
    assert!(
        manifest.contains("memory_gib_min"),
        "must gate on memory_gib_min"
    );
}

#[test]
fn sdr23_module_apply_writes_env_file() {
    // PATH: prepend the compiled selfdefctl binary's directory so
    // apply.sh can find it. CARGO_BIN_EXE_selfdefctl points at the
    // BINARY itself; we want its parent dir on PATH.
    let bin_path = binary();
    let bin_dir = bin_path.parent().unwrap();
    let old_path = std::env::var("PATH").unwrap_or_default();
    let new_path = format!("{}:{old_path}", bin_dir.display());

    let dir = tempfile::tempdir().unwrap();
    let env_file = dir.path().join("hardware-tune.env");

    let apply = module_dir().join("install/apply.sh");
    let out = Command::new(&apply)
        .env("PATH", &new_path)
        .env("SELFDEF_HARDWARE_TUNE_ENV", env_file.to_str().unwrap())
        .output()
        .expect("spawn apply.sh");
    assert!(
        out.status.success(),
        "apply.sh failed: stdout={} stderr={}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr),
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("\"status\":\"ok\""),
        "expected ok status: {stdout}"
    );

    assert!(env_file.exists(), "env file should exist");
    let body = std::fs::read_to_string(&env_file).unwrap();
    assert!(
        body.contains("SELFDEF_HARDWARE_MARCH="),
        "env file missing MARCH key: {body}"
    );
    assert!(
        body.contains("SELFDEF_HARDWARE_CFLAGS="),
        "env file missing CFLAGS key: {body}"
    );
    assert!(
        body.contains("hardware-tune-cache (SD-R23)"),
        "env file missing SD-R23 banner: {body}"
    );
    assert!(
        !body.starts_with("export "),
        "env-file format must NOT have `export` prefix (systemd EnvironmentFile compatibility)"
    );
}

#[test]
fn sdr23_module_apply_dry_run_is_noop() {
    let bin_path = binary();
    let bin_dir = bin_path.parent().unwrap();
    let old_path = std::env::var("PATH").unwrap_or_default();
    let new_path = format!("{}:{old_path}", bin_dir.display());

    let dir = tempfile::tempdir().unwrap();
    let env_file = dir.path().join("hardware-tune.env");
    let apply = module_dir().join("install/apply.sh");
    let out = Command::new(&apply)
        .env("PATH", &new_path)
        .env("SELFDEF_HARDWARE_TUNE_ENV", env_file.to_str().unwrap())
        .env("SELFDEF_DRY_RUN", "1")
        .output()
        .expect("spawn apply.sh");
    assert!(out.status.success(), "apply.sh dry-run rc nonzero");
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("\"status\":\"skipped\""),
        "dry-run should emit skipped status: {stdout}"
    );
    assert!(
        stdout.contains("DRY-RUN"),
        "dry-run message should mention DRY-RUN: {stdout}"
    );
    assert!(!env_file.exists(), "dry-run must not have written the file");
}

#[test]
fn sdr23_module_check_validates_file_shape() {
    let dir = tempfile::tempdir().unwrap();
    let env_file = dir.path().join("hardware-tune.env");

    // Write a valid file by hand (avoid the selfdefctl probe path
    // in this test — exercises check.sh in isolation).
    std::fs::write(
        &env_file,
        "# Generated by selfdef module hardware-tune-cache (SD-R23) at 2026-05-16\n\
         SELFDEF_HARDWARE_MARCH=znver5\n\
         SELFDEF_HARDWARE_CFLAGS=-march=znver5\n",
    )
    .unwrap();

    let check = module_dir().join("install/check.sh");
    let out = Command::new(&check)
        .env("SELFDEF_HARDWARE_TUNE_ENV", env_file.to_str().unwrap())
        .output()
        .expect("spawn check.sh");
    assert!(out.status.success(), "check.sh on valid file rc nonzero");
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("\"status\":\"ok\""),
        "check.sh should report ok: {stdout}"
    );
    assert!(
        stdout.contains("SD-R23-generated"),
        "check.sh should cite the banner: {stdout}"
    );
}

#[test]
fn sdr23_module_check_rejects_missing_file() {
    let dir = tempfile::tempdir().unwrap();
    let env_file = dir.path().join("does-not-exist.env");
    let check = module_dir().join("install/check.sh");
    let out = Command::new(&check)
        .env("SELFDEF_HARDWARE_TUNE_ENV", env_file.to_str().unwrap())
        .output()
        .expect("spawn check.sh");
    assert!(
        !out.status.success(),
        "check.sh on missing file should rc nonzero"
    );
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("\"status\":\"failed\""),
        "missing file should emit failed status: {stdout}"
    );
}

#[test]
fn sdr23_module_check_rejects_file_missing_march_key() {
    let dir = tempfile::tempdir().unwrap();
    let env_file = dir.path().join("hardware-tune.env");
    std::fs::write(&env_file, "JUNK=value\nNOT_THE_RIGHT_KEY=1\n").unwrap();
    let check = module_dir().join("install/check.sh");
    let out = Command::new(&check)
        .env("SELFDEF_HARDWARE_TUNE_ENV", env_file.to_str().unwrap())
        .output()
        .expect("spawn check.sh");
    assert!(!out.status.success(), "check.sh should reject bad file");
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("missing SELFDEF_HARDWARE_MARCH"),
        "should cite missing key: {stdout}"
    );
}

#[test]
fn sdr23_module_uninstall_removes_file_and_is_idempotent() {
    let dir = tempfile::tempdir().unwrap();
    let env_file = dir.path().join("hardware-tune.env");
    std::fs::write(&env_file, "SELFDEF_HARDWARE_MARCH=znver5\n").unwrap();
    let uninstall = module_dir().join("install/uninstall.sh");
    // First run: removes.
    let out = Command::new(&uninstall)
        .env("SELFDEF_HARDWARE_TUNE_ENV", env_file.to_str().unwrap())
        .output()
        .expect("spawn uninstall.sh");
    assert!(out.status.success());
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        stdout.contains("removed"),
        "first run should report removed: {stdout}"
    );
    assert!(!env_file.exists(), "file should be gone");
    // Second run: already-removed → still ok.
    let out2 = Command::new(&uninstall)
        .env("SELFDEF_HARDWARE_TUNE_ENV", env_file.to_str().unwrap())
        .output()
        .expect("spawn uninstall.sh");
    assert!(out2.status.success(), "idempotent uninstall");
    let stdout2 = String::from_utf8_lossy(&out2.stdout);
    assert!(
        stdout2.contains("nothing to remove"),
        "idempotent message: {stdout2}"
    );
}
