#!/usr/bin/env bash
# bitnet-gpu-inference — apply (SD-R28).
#
# Provisions /etc/selfdef/bitnet/ + /var/lib/selfdef/bitnet/ with:
#   - runtime.env   — sources hardware-tune.env + sets BITNET_* paths
#   - schedule.json — per-GPU scheduling map (which GPU hosts which
#                     stage), derived from `selfdefctl hardware probe`
#                     so the load lands on the largest-VRAM card
#
# Idempotent. SELFDEF_DRY_RUN=1 aware.

set -euo pipefail

MODULE="bitnet-gpu-inference"

emit_status() {
    local status="$1"
    local message="${2:-}"
    printf '{"module":"%s","status":"%s","message":"%s"}\n' \
        "${MODULE}" "${status}" "${message}"
}

ETC_DIR="${SELFDEF_BITNET_ETC_DIR:-/etc/selfdef/bitnet}"
STATE_DIR="${SELFDEF_BITNET_STATE_DIR:-/var/lib/selfdef/bitnet}"
ENV_FILE="${ETC_DIR}/runtime.env"
SCHEDULE_FILE="${ETC_DIR}/schedule.json"
TUNE_FILE="${SELFDEF_HARDWARE_TUNE_ENV:-/etc/selfdef/hardware-tune.env}"

DRY_RUN="${SELFDEF_DRY_RUN:-0}"

if ! command -v selfdefctl >/dev/null 2>&1; then
    emit_status "failed" "selfdefctl not on PATH"
    exit 1
fi

if [ "${DRY_RUN}" = "1" ]; then
    emit_status "skipped" "DRY-RUN — would provision ${ETC_DIR} + ${STATE_DIR}"
    exit 0
fi

mkdir -p "${ETC_DIR}" "${STATE_DIR}"
chmod 0755 "${ETC_DIR}" "${STATE_DIR}"

# Atomic env-file write — same pattern as hardware-tune-cache.
tmp_env="$(mktemp "${ENV_FILE}.XXXXXX")"
trap 'rm -f "${tmp_env}"' EXIT
{
    echo "# /etc/selfdef/bitnet/runtime.env"
    # No render-timestamp — defeats cmp -s idempotency (2026-06-06).
    echo "# Generated by selfdef module bitnet-gpu-inference (SD-R28)"
    echo "# Re-run \`selfdefctl modules apply\` to refresh."
    echo
    if [ -r "${TUNE_FILE}" ]; then
        echo "# Sourced from ${TUNE_FILE} (hardware-tune-cache, SD-R23):"
        echo ". \"${TUNE_FILE}\""
    else
        echo "# WARN: ${TUNE_FILE} not found — run \`selfdefctl modules apply --only hardware-tune-cache\`"
    fi
    echo
    echo "# BitNet runtime knobs:"
    echo "BITNET_STATE_DIR=\"${STATE_DIR}\""
    echo "BITNET_SCHEDULE_FILE=\"${SCHEDULE_FILE}\""
    # Pin a sensible default thread count from the tuned env if
    # available, else from nproc.
    echo "BITNET_THREADS=\"\${SELFDEF_HARDWARE_RECOMMENDED_THREADS:-\$(nproc)}\""
} > "${tmp_env}"
chmod 0644 "${tmp_env}"
# Idempotency: skip rewrite when content unchanged.
if [[ -f "${ENV_FILE}" ]] && cmp -s "${tmp_env}" "${ENV_FILE}"; then
    rm -f "${tmp_env}"
else
    mv -f "${tmp_env}" "${ENV_FILE}"
fi
trap - EXIT

# Schedule JSON — per-GPU role assignment. The probe JSON carries
# per-device VRAM (SD-R25); the largest GPU hosts the model, any
# secondary handles auxiliary work (tokenizer / embedding / TTS).
tmp_sched="$(mktemp "${SCHEDULE_FILE}.XXXXXX")"
trap 'rm -f "${tmp_sched}"' EXIT
# Use selfdefctl's hardware export to get the per-GPU caps. If
# that isn't available (older selfdefctl, missing nvidia-smi), emit
# a minimal schedule that round-robins.
caps_json="$(selfdefctl hardware export --stdout 2>/dev/null || true)"

# Default minimal fallback if anything below this path fails.
write_fallback_schedule() {
    cat > "${tmp_sched}" <<'JSON'
{
  "schema_version": "1.0.0",
  "schedule": [{"gpu_index": 0, "role": "model_inference"}],
  "rationale": "capabilities export or python3 unavailable — round-robin fallback"
}
JSON
}

if [ -z "${caps_json}" ] || ! command -v python3 >/dev/null 2>&1; then
    write_fallback_schedule
else
    # Pipe caps JSON to a python helper; fail-soft to the fallback.
    if ! OUT_PATH="${tmp_sched}" printf '%s' "${caps_json}" | OUT_PATH="${tmp_sched}" python3 -c '
import json, sys, os
out_path = os.environ["OUT_PATH"]
caps = json.loads(sys.stdin.read())
devices = (caps.get("gpu") or {}).get("devices", []) or []
ranked = sorted(
    enumerate(devices),
    key=lambda kv: (kv[1].get("vram_bytes") or 0),
    reverse=True,
)
roles = ["model_inference", "auxiliary", "spare"]
schedule = []
for slot, (idx, dev) in enumerate(ranked):
    role = roles[slot] if slot < len(roles) else "spare"
    schedule.append({
        "gpu_index": idx,
        "role": role,
        "model_hint": dev.get("model_hint"),
        "vram_bytes": dev.get("vram_bytes"),
        "power_limit_watts": dev.get("power_limit_watts"),
    })
# No generated_at timestamp — defeats cmp -s idempotency (2026-06-06).
doc = {
    "schema_version": "1.0.0",
    "schedule": schedule,
    "rationale": (
        f"ranked {len(devices)} GPU(s) by VRAM; largest-first wins model_inference"
    ),
}
with open(out_path, "w") as f:
    json.dump(doc, f, indent=2)
'; then
        write_fallback_schedule
    fi
fi
chmod 0644 "${tmp_sched}"
# Idempotency: skip rewrite when content unchanged.
if [[ -f "${SCHEDULE_FILE}" ]] && cmp -s "${tmp_sched}" "${SCHEDULE_FILE}"; then
    rm -f "${tmp_sched}"
else
    mv -f "${tmp_sched}" "${SCHEDULE_FILE}"
fi
trap - EXIT

emit_status "ok" "provisioned ${ETC_DIR}/{runtime.env,schedule.json}"
